<a href="https://colab.research.google.com/github/rida09Heythere/wellness-anxiety-insight-assistant/blob/main/cleaned_excel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!pip install gspread oauth2client

Requirement already satisfied: gspread in /usr/local/lib/python3.12/dist-packages (6.2.1)
Requirement already satisfied: oauth2client in /usr/local/lib/python3.12/dist-packages (4.1.3)
Requirement already satisfied: google-auth>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from gspread) (2.47.0)
Requirement already satisfied: google-auth-oauthlib>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from gspread) (1.4.0)
Requirement already satisfied: httplib2>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from oauth2client) (0.31.2)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python3.12/dist-packages (from oauth2client) (0.6.3)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /usr/local/lib/python3.12/dist-packages (from oauth2client) (0.4.2)
Requirement already satisfied: rsa>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from oauth2client) (4.9.1)
Requirement already satisfied: six>=1.6.1 in /usr/local/lib/python3.12/dist-packages (from oauth2client) (1.17.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from google-auth-oauthlib>=0.4.1->gspread) (2.0.0)
Requirement already satisfied: pyparsing<4,>=3.1 in /usr/local/lib/python3.12/dist-packages (from httplib2>=0.9.1->oauth2client) (3.3.2)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.3.1)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2026.5.20)
Requirement already satisfied: gspread in /usr/local/lib/python3.12/dist-packages (6.2.1)
Requirement already satisfied: oauth2client in /usr/local/lib/python3.12/dist-packages (4.1.3)
Requirement already satisfied: google-auth>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from gspread) (2.47.0)
Requirement already satisfied: google-auth-oauthlib>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from gspread) (1.4.0)
Requirement already satisfied: httplib2>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from oauth2client) (0.31.2)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python3.12/dist-packages (from oauth2client) (0.6.3)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /usr/local/lib/python3.12/dist-packages (from oauth2client) (0.4.2)
Requirement already satisfied: rsa>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from oauth2client) (4.9.1)
Requirement already satisfied: six>=1.6.1 in /usr/local/lib/python3.12/dist-packages (from oauth2client) (1.17.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from google-auth-oauthlib>=0.4.1->gspread) (2.0.0)
Requirement already satisfied: pyparsing<4,>=3.1 in /usr/local/lib/python3.12/dist-packages (from httplib2>=0.9.1->oauth2client) (3.3.2)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.3.1)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2026.5.20)

In [1]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials
scope=["https://spreadsheets.google.com/feeds",
       "https://www.googleapis.com/auth/drive"]
creds=ServiceAccountCredentials.from_json_keyfile_name("cycle-tracker-r.json",scope)
client=gspread.authorize(creds)

sheet = client.open("Anxiety-Tracker-data").worksheet("Health Responses")
print("connected successfully")

connected successfully

In [2]:
import pandas as pd
print(sheet.get_all_records)
df=pd.DataFrame(sheet.get_all_records())
print(df.columns)

<bound method Worksheet.get_all_records of <Worksheet 'Health Responses' id:2089203399>>
Index(['Date', 'Gender', 'Name', 'Cycle Phase', 'Sleep Hrs/Day',
       'Exercise Frequency', 'Anxiety Score (1-10)', 'Anxiety Triggers',
       'Coping Methods', 'Suggestion Helped', 'Most Anxious Phase',
       'Symptoms during anxious phase'],
      dtype='object')

In [3]:
from collections import Counter
all_triggers=[]
for triggers in df["Anxiety Triggers"]:
    all_triggers.extend([t.strip() for t in triggers.split(",") if t.strip()]) # Filter out empty strings
triggers_counts=Counter(all_triggers)
trigger_counts=pd.Series(Counter(all_triggers)).sort_values(ascending=False)
print(trigger_counts)

trigger_df=pd.DataFrame({"Triggers":all_triggers})
trigger_df.head()

Relationship        12
Career              10
Financial            9
Family               8
Future               7
Health               6
Low self-esteem      4
Studies              4
Social               2
Responsibilities     1
Failing              1
none                 1
Low self esteem      1
My whole life        1
dtype: int64

          Triggers
0        Financial
1           Health
2     Relationship
3  Low self-esteem
4           Future

In [5]:
trigger_df.to_excel("cleaned_triggers.xlsx",index="False")
trigger_df.head(20)

            Triggers
0          Financial
1             Health
2       Relationship
3    Low self-esteem
4             Future
5             Family
6            Studies
7             Career
8             Family
9             Future
10      Relationship
11  Responsibilities
12      Relationship
13            Career
14            Health
15           Failing
16            Career
17         Financial
18         Financial
19         Financial

In [ ]:
cleaned_triggers.xlsx

In [7]:
from collections import Counter
all_coping=[]
for coping in df["Coping Methods"]:
  all_coping.extend(c.strip() for c in coping.split(",") if c.strip())
coping_counts=Counter(all_coping)
coping_counts=pd.Series(Counter(all_coping)).sort_values(ascending=False)
print(coping_counts)
coping_df=pd.DataFrame({"Coping Methods":all_coping})
coping_df.to_excel("cleaned_coping.xlsx",index=False)
coping_df.head()

Sleeping                    11
Eating                      10
Music                        6
Exercise                     5
Droomscroll/netflix          4
Prayer                       3
Travelling                   3
Talking to friend/family     2
Self harm                    2
none                         1
Gaming                       1
Prayers                      1
dtype: int64

        Coping Methods
0               Prayer
1                Music
2               Eating
3             Sleeping
4  Droomscroll/netflix

In [10]:
all_emotions=[]
for emotion in df["Symptoms during anxious phase"]:
  all_emotions.extend(e.strip() for e in str(emotion).split(",")if e.strip())
emotion_df=pd.DataFrame({"Emotion":all_emotions})
emotion_df.to_excel("cleaned_emotions.xlsx",index=False)
emotion_df.head()

      Emotion
0      Stress
1    Bad mood
2      Freaky
3      Cranky
4  Sad scared