<a href="https://colab.research.google.com/github/rida09Heythere/mental-health-cycle-tracker/blob/main/data_cleaning_newV2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install gspread oauth2client

Requirement already satisfied: gspread in /usr/local/lib/python3.12/dist-packages (6.2.1)
Collecting oauth2client
  Downloading oauth2client-4.1.3-py2.py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: google-auth>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from gspread) (2.47.0)
Requirement already satisfied: google-auth-oauthlib>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from gspread) (1.4.0)
Requirement already satisfied: httplib2>=0.9.1 in /usr/lib/python3/dist-packages (from oauth2client) (0.20.2)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python3.12/dist-packages (from oauth2client) (0.6.3)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /usr/local/lib/python3.12/dist-packages (from oauth2client) (0.4.2)
Requirement already satisfied: rsa>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from oauth2client) (4.9.1)
Requirement already satisfied: six>=1.6.1 in /usr/local/lib/python3.12/dist-packages (from oauth2client) (1.17.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from google-auth-oauthlib>=0.4.1->gspread) (2.0.0)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /usr/local/lib/python3.12/dist-packages (from httplib2>=0.9.1->oauth2client) (3.3.2)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.3.1)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2026.5.20)
Downloading oauth2client-4.1.3-py2.py3-none-any.whl (98 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.2/98.2 kB 4.5 MB/s eta 0:00:00
Installing collected packages: oauth2client
Successfully installed oauth2client-4.1.3

In [18]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials
scope=["https://spreadsheets.google.com/feeds",
       "https://www.googleapis.com/auth/drive"]
creds=ServiceAccountCredentials.from_json_keyfile_name("cycle-tracker-r.json",scope)
client=gspread.authorize(creds)

sheet = client.open("Cycle-Tracker-data").worksheet("Health Responses")
print("connected successfully")

connected successfully

In [19]:
print(sheet.get_all_records)

<bound method Worksheet.get_all_records of <Worksheet 'Health Responses' id:2089203399>>

In [20]:
print(sheet.get_all_records())
import pandas as pd
data=sheet.get_all_records()
df=pd.DataFrame(data)
print(df.head())
print(df.shape)
print(df.columns)
print(df.dtypes)
print(df.isnull().sum())

[{'Date': '2026-06-01', 'Name': 'Rida', 'Current Phase': 'Follicular', 'Sleep (hrs/day)': 9, 'Exercise Frequency': 'Never', 'Anxiety Score (1-10)': 6, 'Anxiety Trigger': 'Future', 'Coping Methods': 'Music, Eating, Watching phone/movies etc, Sleeping, Travelling', 'Previous Suggestion Helped': 'First time', 'Most Anxious Phase': 'Luteal', 'Symptoms/Experience': 'Bad mood, Low energy, Dull, Angry'}, {'Date': '2026-06-01', 'Name': 'Riya', 'Current Phase': 'Ovulation', 'Sleep (hrs/day)': 9, 'Exercise Frequency': 'Never', 'Anxiety Score (1-10)': 10, 'Anxiety Trigger': 'Family', 'Coping Methods': 'Music, Watching phone/movies etc, Sleeping, Eating', 'Previous Suggestion Helped': 'First time', 'Most Anxious Phase': 'Follicular', 'Symptoms/Experience': 'Bad mood'}, {'Date': '2026-06-01', 'Name': 'Shazfa', 'Current Phase': 'Menstrual', 'Sleep (hrs/day)': 11, 'Exercise Frequency': '1-2 days a week', 'Anxiety Score (1-10)': 7, 'Anxiety Trigger': 'Family', 'Coping Methods': 'Watching phone/movies etc, Eating', 'Previous Suggestion Helped': 'First time', 'Most Anxious Phase': 'Luteal', 'Symptoms/Experience': 'Bad mood, Low energy, Sad, Stress'}, {'Date': '2026-06-01', 'Name': 'Tina', 'Current Phase': 'Luteal', 'Sleep (hrs/day)': 6, 'Exercise Frequency': '1-2 days a week', 'Anxiety Score (1-10)': 7, 'Anxiety Trigger': 'Health', 'Coping Methods': 'Exercise, Meditation, Prayers, Music', 'Previous Suggestion Helped': 'First time', 'Most Anxious Phase': 'Follicular', 'Symptoms/Experience': 'More energy, Bad mood, Stress, Freaky, Motivated'}, {'Date': '2026-06-01', 'Name': 'Samia', 'Current Phase': 'Ovulation', 'Sleep (hrs/day)': 6, 'Exercise Frequency': 'Never', 'Anxiety Score (1-10)': 6, 'Anxiety Trigger': 'Relationship', 'Coping Methods': 'Music, Talking to friend/family, Eating, Watching phone/movies etc, Sleeping', 'Previous Suggestion Helped': 'First time', 'Most Anxious Phase': 'Luteal', 'Symptoms/Experience': 'Cramps, Stress, Angry, Low energy, Bad mood, Dull'}, {'Date': '2026-06-01', 'Name': 'Samayara', 'Current Phase': 'Menstrual', 'Sleep (hrs/day)': 14, 'Exercise Frequency': 'Never', 'Anxiety Score (1-10)': 8, 'Anxiety Trigger': 'Relationship', 'Coping Methods': 'Sleeping, Eating, Watching phone/movies etc, Talking to friend/family', 'Previous Suggestion Helped': 'First time', 'Most Anxious Phase': 'Menstrual', 'Symptoms/Experience': 'Heavy bleeding, Fatigue, Mood swings, Severe cramps'}, {'Date': '2026-06-01', 'Name': 'Fazia', 'Current Phase': 'Menstrual', 'Sleep (hrs/day)': 7, 'Exercise Frequency': 'Never', 'Anxiety Score (1-10)': 7, 'Anxiety Trigger': 'Career', 'Coping Methods': 'Music', 'Previous Suggestion Helped': 'First time', 'Most Anxious Phase': 'Menstrual', 'Symptoms/Experience': 'Bad mood , Regret , irritated , Severe cramps , angry'}, {'Date': '2026-06-01', 'Name': 'Aamna', 'Current Phase': 'Menstrual', 'Sleep (hrs/day)': 7, 'Exercise Frequency': '1-2 days a week', 'Anxiety Score (1-10)': 3, 'Anxiety Trigger': 'Career', 'Coping Methods': 'Sleeping ', 'Previous Suggestion Helped': 'First time', 'Most Anxious Phase': 'Menstrual', 'Symptoms/Experience': 'Low energy , Bad mood , Severe cramps'}, {'Date': '2026-06-01', 'Name': 'Uzma', 'Current Phase': 'Menstrual', 'Sleep (hrs/day)': 6, 'Exercise Frequency': 'Never', 'Anxiety Score (1-10)': 7, 'Anxiety Trigger': 'Responsibilities', 'Coping Methods': 'Prayer', 'Previous Suggestion Helped': 'First time', 'Most Anxious Phase': 'Menstrual', 'Symptoms/Experience': 'Anxiety, Bad mood , Severe Cramps , low energy'}, {'Date': '2026-06-01', 'Name': 'Payal', 'Current Phase': 'Luteal', 'Sleep (hrs/day)': 9, 'Exercise Frequency': '3-5 days a week', 'Anxiety Score (1-10)': 4, 'Anxiety Trigger': 'Financial', 'Coping Methods': 'Exercise, Prayers, Talking to friend/family, Sleeping', 'Previous Suggestion Helped': 'First time', 'Most Anxious Phase': 'Follicular', 'Symptoms/Experience': 'Freaky, Bad mood, Stress, More energy'}, {'Date': '2026-06-01', 'Name': 'Ashiya', 'Current Phase': 'Follicular', 'Sleep (hrs/day)': 5, 'Exercise Frequency': '1-2 days a week', 'Anxiety Score (1-10)': 8, 'Anxiety Trigger': 'Studies', 'Coping Methods': 'Prayers, Sleeping, Watching phone/movies etc', 'Previous Suggestion Helped': 'First time', 'Most Anxious Phase': 'Menstrual', 'Symptoms/Experience': 'Fatigue, Mood swings, Severe cramps, Heavy bleeding'}, {'Date': '2026-06-01', 'Name': 'Pranjal', 'Current Phase': 'Ovulation', 'Sleep (hrs/day)': 10, 'Exercise Frequency': '3-5 days a week', 'Anxiety Score (1-10)': 8, 'Anxiety Trigger': 'Low self-esteem', 'Coping Methods': 'Self harm', 'Previous Suggestion Helped': 'First time', 'Most Anxious Phase': 'Menstrual', 'Symptoms/Experience': 'Heavy bleeding, Fatigue, Severe cramps'}, {'Date': '2026-06-02', 'Name': 'Sufiya', 'Current Phase': 'Luteal', 'Sleep (hrs/day)': 8, 'Exercise Frequency': 'Never', 'Anxiety Score (1-10)': 4, 'Anxiety Trigger': 'Family,Future,Relationship', 'Coping Methods': 'Droom scroll', 'Previous Suggestion Helped': 'First time', 'Most Anxious Phase': 'Menstrual', 'Symptoms/Experience': 'Cramps, Stress, Angry, Low energy, Bad mood, Dull'}, {'Date': '2026-06-02', 'Name': 'Reena', 'Current Phase': 'Ovulation', 'Sleep (hrs/day)': 6, 'Exercise Frequency': 'Never', 'Anxiety Score (1-10)': 6, 'Anxiety Trigger': 'Studies', 'Coping Methods': 'Music, Talking to friend/family', 'Previous Suggestion Helped': 'First time', 'Most Anxious Phase': 'Luteal', 'Symptoms/Experience': 'Sad, Cramps, Bad mood'}, {'Date': '2026-06-02', 'Name': 'Naaz', 'Current Phase': 'Ovulation', 'Sleep (hrs/day)': 3, 'Exercise Frequency': 'Never', 'Anxiety Score (1-10)': 3, 'Anxiety Trigger': 'Social', 'Coping Methods': 'Travelling, Eating, Talking to friend/family', 'Previous Suggestion Helped': 'First time', 'Most Anxious Phase': 'Menstrual', 'Symptoms/Experience': 'Heavy bleeding, Fatigue'}, {'Date': '2026-06-02', 'Name': 'Nisha', 'Current Phase': 'Menstrual', 'Sleep (hrs/day)': 6, 'Exercise Frequency': 'Never', 'Anxiety Score (1-10)': 7, 'Anxiety Trigger': 'Financial', 'Coping Methods': 'Music, Eating', 'Previous Suggestion Helped': 'First time', 'Most Anxious Phase': 'Menstrual', 'Symptoms/Experience': 'Severe cramps, Heavy bleeding, Mood swings'}]
         Date    Name Current Phase  Sleep (hrs/day) Exercise Frequency  \
0  2026-06-01    Rida    Follicular                9              Never
1  2026-06-01    Riya     Ovulation                9              Never
2  2026-06-01  Shazfa     Menstrual               11    1-2 days a week
3  2026-06-01    Tina        Luteal                6    1-2 days a week
4  2026-06-01   Samia     Ovulation                6              Never

   Anxiety Score (1-10) Anxiety Trigger  \
0                     6          Future
1                    10          Family
2                     7          Family
3                     7          Health
4                     6    Relationship

                                      Coping Methods  \
0  Music, Eating, Watching phone/movies etc, Slee...
1  Music, Watching phone/movies etc, Sleeping, Ea...
2                  Watching phone/movies etc, Eating
3               Exercise, Meditation, Prayers, Music
4  Music, Talking to friend/family, Eating, Watch...

  Previous Suggestion Helped Most Anxious Phase  \
0                 First time             Luteal
1                 First time         Follicular
2                 First time             Luteal
3                 First time         Follicular
4                 First time             Luteal

                                 Symptoms/Experience
0                  Bad mood, Low energy, Dull, Angry
1                                           Bad mood
2                  Bad mood, Low energy, Sad, Stress
3   More energy, Bad mood, Stress, Freaky, Motivated
4  Cramps, Stress, Angry, Low energy, Bad mood, Dull
(16, 11)
Index(['Date', 'Name', 'Current Phase', 'Sleep (hrs/day)',
       'Exercise Frequency', 'Anxiety Score (1-10)', 'Anxiety Trigger',
       'Coping Methods', 'Previous Suggestion Helped', 'Most Anxious Phase',
       'Symptoms/Experience'],
      dtype='object')
Date                          object
Name                          object
Current Phase                 object
Sleep (hrs/day)                int64
Exercise Frequency            object
Anxiety Score (1-10)           int64
Anxiety Trigger               object
Coping Methods                object
Previous Suggestion Helped    object
Most Anxious Phase            object
Symptoms/Experience           object
dtype: object
Date                          0
Name                          0
Current Phase                 0
Sleep (hrs/day)               0
Exercise Frequency            0
Anxiety Score (1-10)          0
Anxiety Trigger               0
Coping Methods                0
Previous Suggestion Helped    0
Most Anxious Phase            0
Symptoms/Experience           0
dtype: int64

In [21]:
df.describe()

       Sleep (hrs/day)  Anxiety Score (1-10)
count        16.000000             16.000000
mean          7.625000              6.312500
std           2.655184              1.956826
min           3.000000              3.000000
25%           6.000000              5.500000
50%           7.000000              7.000000
75%           9.000000              7.250000
max          14.000000             10.000000

In [22]:
df.duplicated().sum()
print(df["Current Phase"].unique())
print(df["Exercise Frequency"].unique())
print(df["Anxiety Trigger"].unique())
print(df["Previous Suggestion Helped"].unique())
print(df["Most Anxious Phase"].unique())

['Follicular' 'Ovulation' 'Menstrual' 'Luteal']
['Never' '1-2 days a week' '3-5 days a week']
['Future' 'Family' 'Health' 'Relationship' 'Career' 'Responsibilities'
 'Financial' 'Studies' 'Low self-esteem' 'Family,Future,Relationship'
 'Social']
['First time']
['Luteal' 'Follicular' 'Menstrual']

In [23]:
phase_anxiety=df.groupby("Current Phase")["Anxiety Score (1-10)"].mean()
print(phase_anxiety)
df["Current Phase"].value_counts()
df["Anxiety Trigger"].value_counts()
df["Coping Methods"].value_counts()

Current Phase
Follicular    7.0
Luteal        5.0
Menstrual     6.5
Ovulation     6.6
Name: Anxiety Score (1-10), dtype: float64

Coping Methods
Music, Eating, Watching phone/movies etc, Sleeping, Travelling                  1
Music, Watching phone/movies etc, Sleeping, Eating                              1
Watching phone/movies etc, Eating                                               1
Exercise, Meditation, Prayers, Music                                            1
Music, Talking to friend/family, Eating, Watching phone/movies etc, Sleeping    1
Sleeping, Eating, Watching phone/movies etc, Talking to friend/family           1
Music                                                                           1
Sleeping                                                                        1
Prayer                                                                          1
Exercise, Prayers, Talking to friend/family, Sleeping                           1
Prayers, Sleeping, Watching phone/movies etc                                    1
Self harm                                                                       1
Droom scroll                                                                    1
Music, Talking to friend/family                                                 1
Travelling, Eating, Talking to friend/family                                    1
Music, Eating                                                                   1
Name: count, dtype: int64

In [29]:
all_methods=df["Coping Methods"].str.split(",").explode()
all_methods=all_methods.str.strip()
all_methods=all_methods.replace({"Prayers":"Prayer","Travelling":"Traveling"})
print(all_methods.value_counts())

Coping Methods
Music                        7
Eating                       7
Sleeping                     7
Watching phone/movies etc    6
Talking to friend/family     5
Prayer                       4
Traveling                    2
Exercise                     2
Meditation                   1
Self harm                    1
Droom scroll                 1
Name: count, dtype: int64